name: Run PnL Automation

on:
  schedule:
    - cron: '*/15 * * * *' # runs every 15 minutes
  workflow_dispatch:       # allows manual run in Actions tab

jobs:
  pnl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Write Google Service Account file
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}" > service_account.json

      - name: Run PnL Script
        env:
          DIGICASH_API_USER: ${{ secrets.DIGICASH_API_USER }}
          DIGICASH_API_PASS: ${{ secrets.DIGICASH_API_PASS }}
          MERCHANT_CONFIG_SHEET_URL: ${{ secrets.MERCHANT_CONFIG_SHEET_URL }}
        run: python main.py